---
.travis.yml:
   secure: "p67QoIuj9j2DtGt39bZt/YSj+ggMA/fJHmH5DB30QMnvFw79k4SSNnoycwTnuLvNZIbqzUkJCU7TtXiJC0rFiJTgPWM9+uik4jB7sZWZ4ynoMOyT96PZwCePozhnqmMen/4dDRRKHGVT9GQbw/37EolWODrNswRe9JBhjMRlHZs="
   docker_sets:
      - set: centos6-64
      - set: centos7-64
